[package]
name = "gyatt-fryer-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde_json = "1.0.117"
circuit-checker = { path = "../circuit-checker" }
acir.workspace = true
nargo.workspace = true

